[package]
name = "memsec"
version = "0.1.4"
authors = ["quininer kel <quininer@live.com>"]
description = "Rust implementation `libsodium/utils`."
repository = "https://github.com/quininer/memsec"
license = "MIT"

[dependencies]
libc = "0.2"
rand = "0.3"
winapi = "0.2"
kernel32-sys = "0.2"

[dev-dependencies]
nix = "0.6"
# libsodium-sys = "0.0.10"
